"""
Activity analyser — classifies detections into suspicious activity events.

Combines weapon/concealment detections with loitering events and applies
temporal filtering (alert cooldown) to avoid alert storms.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from src.detector import Detection
from src.logger import get_logger
from src.loitering_detector import LoiterEvent
from src.zones import ZoneManager

logger = get_logger(__name__)

# Mapping from detected class name to activity category
WEAPON_CLASSES = {"gun", "knife"}
CONCEALMENT_CLASSES = {"helmet", "mask"}

ACTIVITY_LABELS: Dict[str, str] = {
    "gun": "Weapon Detected",
    "knife": "Weapon Detected",
    "helmet": "Face Concealment Detected",
    "mask": "Face Concealment Detected",
    "loitering": "Loitering Detected",
}


@dataclass
class ActivityEvent:
    """A suspicious activity event ready for alert generation."""

    activity: str          # human-readable label, e.g. "Weapon Detected"
    activity_type: str     # "weapon" | "concealment" | "loitering"
    detected_object: str   # e.g. "gun", "mask", "person"
    confidence: float
    bbox: tuple
    zone_name: Optional[str] = None
    person_id: Optional[int] = None
    timestamp: float = field(default_factory=time.time)
    metadata: Dict = field(default_factory=dict)


class ActivityAnalyzer:
    """
    Analyses per-frame detections and loitering events for suspicious behaviour.

    Implements temporal filtering so the same (class, zone) combination
    cannot trigger repeated alerts within ``alert_cooldown_seconds``.
    """

    def __init__(
        self,
        zone_manager: ZoneManager,
        alert_cooldown_seconds: float = 30.0,
        weapon_confidence_threshold: float = 0.6,
        concealment_confidence_threshold: float = 0.65,
    ) -> None:
        """
        Initialise the analyser.

        Args:
            zone_manager: Zone definitions used to tag alert locations.
            alert_cooldown_seconds: Minimum seconds between repeated alerts
                                    for the same (class, zone) combination.
            weapon_confidence_threshold: Minimum confidence for weapon detections.
            concealment_confidence_threshold: Minimum confidence for concealment
                                              detections.
        """
        self.zone_manager = zone_manager
        self.alert_cooldown_seconds = alert_cooldown_seconds
        self.weapon_conf_threshold = weapon_confidence_threshold
        self.concealment_conf_threshold = concealment_confidence_threshold

        # (activity_type, class_name, zone_name) → last alert timestamp
        self._last_alert: Dict[tuple, float] = {}

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def analyze(
        self,
        detections: List[Detection],
        loiter_events: Optional[List[LoiterEvent]] = None,
    ) -> List[ActivityEvent]:
        """
        Produce activity events for a single frame.

        Args:
            detections: All detections from the current frame.
            loiter_events: Loitering events generated by
                           :class:`~src.loitering_detector.LoiteringDetector`.

        Returns:
            List of :class:`ActivityEvent` that passed cooldown filtering.
        """
        current_time = time.time()
        events: List[ActivityEvent] = []

        # --- Weapon and concealment detections ---
        for det in detections:
            if det.is_person:
                continue

            event = self._classify_detection(det, current_time)
            if event is not None:
                events.append(event)

        # --- Loitering events ---
        for loiter in (loiter_events or []):
            key = ("loitering", "person", loiter.zone_name)
            if self._can_alert(key, current_time):
                events.append(
                    ActivityEvent(
                        activity="Loitering Detected",
                        activity_type="loitering",
                        detected_object="person",
                        confidence=1.0,
                        bbox=loiter.bbox,
                        zone_name=loiter.zone_name,
                        person_id=loiter.track_id,
                        metadata={"duration_seconds": round(loiter.duration, 1)},
                    )
                )
                self._last_alert[key] = current_time
                logger.debug(
                    "Loitering event queued for track %d in zone '%s'.",
                    loiter.track_id,
                    loiter.zone_name,
                )

        return events

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _classify_detection(
        self, det: Detection, current_time: float
    ) -> Optional[ActivityEvent]:
        """Map a detection to an ActivityEvent or return None if filtered."""
        cls = det.class_name.lower()

        if cls in WEAPON_CLASSES:
            if det.confidence < self.weapon_conf_threshold:
                return None
            activity_type = "weapon"
        elif cls in CONCEALMENT_CLASSES:
            if det.confidence < self.concealment_conf_threshold:
                return None
            activity_type = "concealment"
        else:
            return None

        zones = self.zone_manager.zones_containing_bbox(det.bbox)
        zone_name = zones[0] if zones else "unknown"

        key = (activity_type, cls, zone_name)
        if not self._can_alert(key, current_time):
            return None

        self._last_alert[key] = current_time
        event = ActivityEvent(
            activity=ACTIVITY_LABELS.get(cls, "Suspicious Activity"),
            activity_type=activity_type,
            detected_object=cls,
            confidence=det.confidence,
            bbox=det.bbox,
            zone_name=zone_name,
        )
        logger.info(
            "%s detected (conf=%.2f) in zone '%s'.",
            event.activity,
            det.confidence,
            zone_name,
        )
        return event

    def _can_alert(self, key: tuple, current_time: float) -> bool:
        """Return True if the cooldown has elapsed for *key*."""
        last = self._last_alert.get(key, 0.0)
        return (current_time - last) >= self.alert_cooldown_seconds
